# Generated by Django 3.1.7 on 2021-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0002_post_title_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_blog',
            new_name='title_tag',
        ),
    ]
