# Generated by Django 3.1.7 on 2021-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
