# Generated by Django 3.1.7 on 2021-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0014_auto_20210525_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
